set(_CATKIN_CURRENT_PACKAGE "cmd_vel_test")
set(cmd_vel_test_VERSION "0.0.0")
set(cmd_vel_test_MAINTAINER "l <l@todo.todo>")
set(cmd_vel_test_PACKAGE_FORMAT "2")
set(cmd_vel_test_BUILD_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(cmd_vel_test_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(cmd_vel_test_BUILDTOOL_DEPENDS "catkin")
set(cmd_vel_test_BUILDTOOL_EXPORT_DEPENDS )
set(cmd_vel_test_EXEC_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(cmd_vel_test_RUN_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(cmd_vel_test_TEST_DEPENDS )
set(cmd_vel_test_DOC_DEPENDS )
set(cmd_vel_test_URL_WEBSITE "")
set(cmd_vel_test_URL_BUGTRACKER "")
set(cmd_vel_test_URL_REPOSITORY "")
set(cmd_vel_test_DEPRECATED "")